version: '3.2'
services:
  notebook:
    build: .
    tty: true
    volumes:
      - type: bind
        source: "./pyproject.toml"
        target: "/app/pyproject.toml"
      - type: bind
        source: "./input/"
        target: "/app/input/"
      - type: bind
        source: "./output/"
        target: "/app/output/"
      - type: bind
        source: "./notebooks"
        target: "/app/notebooks"
    entrypoint: >
      jupyter lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
